[feat] 1주차 과제
AND-SOPT-ANDROID/seungbeom-lee pull request #3
Opened 2024-10-10 07:23 UTC by beom84

## Related issue 🛠
- closed #1 

## Work Description ✏️

- SignUpScreen 구현
이메일 비밀번호 형식에 맞지 않을 경우 Toast 메세지
회원가입이 성공하면 Toast 메세지
회원가입 규칙은 정규식으로 처리
비밀번호 visible 처리
putExtra로 이메일, 비밀번호 정보 넘겨줌

- LogInScreen 구현
getExtra로 이메일, 비밀번호 가져와서 로그인 로직 구현
회원가입 안하고 로그인 시도시 Snackbar 메세지 발생 , 회원가입 버튼 누르면 SignUpActivity로 이동
로그인 실패시 Snackbar 메세지 , 성공시 Toast 메세지
회원가입 클릭시 SignUpScreen으로 이동
로그인 성공 시 스택 삭제 -> 뒤로가기 하면 로그인뷰가 아니라 앱 종료

- MyPage구현
getExtra로 이메일 정보 출력

## Screenshot 📸
[<img src="" width="360"/>
](https://github.com/user-attachments/assets/feb4f06f-7fb8-4700-9972-494787ac1523)

## Uncompleted Tasks 😅

## To Reviewers 📢
첫과제 열심히 해보았습니다 마구 때려주세요!

2024-10-10 15:31 UTC, Hyobeen-Park reviewed
1주차 과제 수고하셨습니다!! 너무 잘하셨는데요?!?? 패키지랑 컴포넌트 분리한거 진짜 최고여요 

지금 패키지가 screen들만 따로 모아두신 것 같은데 이렇게 패키징하신 이유가 궁금해요!!(진짜 단순 호기심입니당)

2024-10-10 15:31 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/LogInActivity.kt
> +
별건 아니지만 저는 불필요한 줄바꿈은 최대한 없애주는 편이에요! 줄 바꿈도 커밋할 때 인식이 되기 때문에 나중에 불필요한 커밋이 생길 수 있어서요!!

2024-10-10 15:31 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/SignUpActivity.kt
> +                        putExtra("password", password.trim())
`id`, `password` 와 같은 키값은 상수화 해보는거 어떨까요?? 다른 곳에서도 쉽게 접근이 가능하고 가독성도 좋아져요! ~~(+오타로 인한 삽질도 막을 수 있어요....)~~

2024-10-10 15:31 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/SignUpActivity.kt
> +                        putExtra("password", password.trim())
오 trim() 사용한거 넘 좋네요!!

2024-10-10 15:31 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/component/TextFieldCustom.kt
> +fun TextAndContent(text: String, content: @Composable () -> Unit) {
오 param으로 `@Composable` 받아오는거 짱이에여! 재사용하기 아주 좋을 것 같아요!

2024-10-10 15:31 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/component/TextFieldCustom.kt
컴포넌트 분리까지 하다니,,, 인재다 인재!!!!!

2024-10-10 15:31 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/component/TextFieldCustom.kt
> +fun TextField_Custom(
이름을 custom이라고 짓는 것보다 어떤 컴포넌트인지 명시해주면 가독성이 더 좋아져요!! ex. `EmailTextField`

그리고 컴포저블 함수에는 Pascal Case를 사용하기 때문에 언더바 없이 `TextFieldCustom` 이런 느낌으로 네이밍 해주시면 좋아요!

2024-10-10 15:31 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/component/TextFieldCustom.kt
> +    trailingIcon: @Composable (() -> Unit)? = null
이 친구를 nullable 설정하신 이유가 궁금해요!!(진짜 단순 호기심입니다ㅎㅎ)

2024-10-10 15:31 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/component/TextFieldCustom.kt
> +fun TextField_Custom2(
이것도!!! 위에 있는 `TextField_Custom` 과 마찬가지로 네이밍 수정 해주세요!!

2024-10-10 15:31 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/screen/LogInScreen.kt
> +                text = "Wavve",
문자열은 string으로 추출해주는 것이 좋을 것 같아요!! 가독성도 좋아지고 추후에 동일한 문자열을 사용할 일이 생기면 또 추가할 필요 없이 바로 사용할 수 있어서 확장성도 좋아져요😊

2024-10-10 15:31 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/screen/LogInScreen.kt
> +                        if (signUpId.isNotEmpty()) {
`isEmpty` 와 `isBlank` 의 차이점을 알고 계신가요?!?? 혹시 모르신다면!!! 한번 알아보는 것도 좋을 것 같아요 생각보다 자주 쓰이기도 하고 상황에 따라 적절히 활용하면 아주 좋답니다😊

2024-10-10 15:31 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/screen/LogInScreen.kt
> +                    onClick = {
`onClick` 내부에 너무 많은 기능들이 있는 것 같아요! 함수로 분리해보는건 어떨까요? 함수화를 하면 가독성과 유지보수에 좋습니다!

2024-10-10 15:31 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/screen/LogInScreen.kt
> +                                val intent2 = Intent(context, MyActivity::class.java).apply {
오!! 스코프 함수 사용한거 너무 좋아요!!

2024-10-10 15:31 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/screen/LogInScreen.kt
> +                                context.startActivity(intent2)
`startActivity()` 함수도 스코프 함수 내부에 넣을 수 있어요! 그러면 `intent2` 객체를 생성하지 않아도 된답니다😊

2024-10-10 15:31 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/screen/LogInScreen.kt
> +                        .height(50.dp)
버튼 크기를 고정하셨네요..! 이렇게 크기를 고정해두면 기기의 폰트 크기가 커졌을 때 버튼보다 내부에 있는 텍스트가 더 커지는 문제가 발생할 수도 있어요!! 높이를 지정하기 보다 `padding`을 활용해서 크기를 조절해 보는 것은 어떨까요?

2024-10-10 15:31 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/screen/LogInScreen.kt
> +                        .width(70.dp)
이 부분도!! 기기의 크기가 커지면 양 옆으로 빈 공간이 생길 수 있어요!! 기기대응을 위해 다른 방법을 찾아봅시다!!

2024-10-10 15:31 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/screen/LogInScreen.kt
> +                Spacer(Modifier.padding(3.dp))
이 부분은 `Image`에 `padding`을 적용하는 방식으로 대체할 수 있어요!! 추가적으로 `Spacer`와 `padding`의 차이점도 함께 공부해보면 좋을 것 같네요😊

2024-10-10 15:31 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/screen/MyProfileScreen.kt
> +            )
이 부분!! Spacer를 사용하지 않고 padding만을 이용해서 구현이 가능한데요!!! 한번 고민해보면 좋을 것 같네요ㅎㅎ

2024-10-10 15:31 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/screen/SignUpScreen.kt
> +            Spacer(modifier)
오 여기에는 인자로 받은` modifier`를 사용하셨네요!! 이유가 궁금해요~!

2024-10-10 15:31 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/screen/SignUpScreen.kt
> +        //
여기 주석 사용하지 않는다면 없애주세요!

2024-10-10 15:31 UTC, Hyobeen-Park commented on app/src/main/res/values/colors.xml
> +    <color name="profile_gray_25">#FF252525</color>
디테일 미쳤다..!! 진짜 짱이에요👍🏻

2024-10-10 15:31 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/component/TextFieldCustom.kt
> +                    .padding(7.dp), color = colorResource(R.color.gray_a3)
윈도우는 Ctrl + Alt + L  맥은 Command + Option + L 
이 단축키 사용하면 코드 정리가 자동으로 돼요!

2024-10-11 04:43 UTC, beom84 commented on app/src/main/java/org/sopt/and/SignUpActivity.kt
> +                        putExtra("password", password.trim())
상수화 너무 좋습니다 메모메모..!

2024-10-11 04:45 UTC, beom84 commented on app/src/main/java/org/sopt/and/screen/LogInScreen.kt
> +                text = "Wavve",
그렇다면 모든 문자열을 추출하는것이 좋나요? 아니면 나중에 사용할 것 같은것 만 추출하나요?

2024-10-11 04:49 UTC, beom84 commented on app/src/main/java/org/sopt/and/screen/LogInScreen.kt
> +                        if (signUpId.isNotEmpty()) {
방금 알아보았습니다! 
isEmpty는 문자열의 길이가 0인 경우에 true
isBlank는 문자열이 비어 있거나 빈공백으로 이루어져 있을때 true!
메모메모...!

2024-10-11 04:51 UTC, beom84 commented on app/src/main/java/org/sopt/and/screen/LogInScreen.kt
> +                                context.startActivity(intent2)
그러네요!! 메모메모...

2024-10-11 04:53 UTC, beom84 commented on app/src/main/java/org/sopt/and/screen/MyProfileScreen.kt
> +            )
Spacer를 2개 사용하지않고 하나의 spacer만을 이용해서 구현 가능하다는 뜻인가요???

2024-10-11 04:54 UTC, beom84 commented on app/src/main/java/org/sopt/and/screen/SignUpScreen.kt
> +        //
네! 잘 확인하겠습니다!!!

2024-10-11 04:57 UTC, beom84 commented on app/src/main/java/org/sopt/and/screen/SignUpScreen.kt
> +            Spacer(modifier)
잘 못 넣었습니다..수정수정..

2024-10-11 05:04 UTC, beom84 commented on app/src/main/java/org/sopt/and/screen/LogInScreen.kt
> +                        .height(50.dp)
저는 heightIn이라는 함수를 사용해보았는데 괜찮나요? padding은 모르겠어요..

2024-10-11 05:10 UTC, beom84 commented on app/src/main/java/org/sopt/and/component/TextFieldCustom.kt
> +    trailingIcon: @Composable (() -> Unit)? = null
아이디와 비번 두개의 textfield에 같이 사용하려고 nullable 설정 해놓았습니다!

2024-10-11 05:15 UTC, beom84 commented on app/src/main/java/org/sopt/and/component/TextFieldCustom.kt
> +fun TextField_Custom(
넵..!

2024-10-11 05:17 UTC, beom84 commented on app/src/main/java/org/sopt/and/component/TextFieldCustom.kt
> +fun TextField_Custom2(
수정완료..!

2024-10-11 05:17 UTC, beom84 commented on app/src/main/java/org/sopt/and/component/TextFieldCustom.kt
> +                    .padding(7.dp), color = colorResource(R.color.gray_a3)
넵!

2024-10-11 05:17 UTC, beom84 commented on app/src/main/java/org/sopt/and/component/TextFieldCustom.kt
> +fun TextAndContent(text: String, content: @Composable () -> Unit) {
야호!

2024-10-11 05:23 UTC, beom84 commented on app/src/main/java/org/sopt/and/screen/LogInScreen.kt
> +                    onClick = {
넵..! 기능은 쪼개서 함수로.. 메모메모..

2024-10-11 05:27 UTC, beom84 commented on app/src/main/java/org/sopt/and/screen/LogInScreen.kt
> +                Spacer(Modifier.padding(3.dp))
불필요한 component는 쓰지않기..메모하겠습니다!

2024-10-11 05:33 UTC, beom84 commented on app/src/main/java/org/sopt/and/screen/LogInScreen.kt
> +                Spacer(Modifier.padding(3.dp))
spacer 와 padding은 화면을 touch할때 컴포넌트의 크기에 영향을 준다는 차이점이 있군요..!
찾아보니 spaceHosting이라는 방법도 있던데 효빈님은 보통 무엇을 많이 사용하시나요?

2024-10-11 05:37 UTC, beom84 commented
> 1주차 과제 수고하셨습니다!! 너무 잘하셨는데요?!?? 패키지랑 컴포넌트 분리한거 진짜 최고여요
> 
> 지금 패키지가 screen들만 따로 모아두신 것 같은데 이렇게 패키징하신 이유가 궁금해요!!(진짜 단순 호기심입니당)
>
> 보기가 편해서... 모아놓았습니다...

2024-10-12 10:58 UTC, l2hyunwoo commented
안녕하세요. 명예 OB 리뷰어 이현우입니다. 앞으로 N번의 과제동안 잘 부탁드리겠습니다. 🙇🏻 

해당 PR의 리뷰는 금잔디조 내 모든 분들의 리뷰가 완료된 후 작성하도록 하겠습니다.

2024-10-12 21:16 UTC, MinseoSONG reviewed
컴포넌트 분리에 색상값 정리까지 .. !
1주차 맞나요 ? ? 꼼꼼킹 ... ..
2주차도 같이 화이팅해봐요 ~~~!

2024-10-12 21:16 UTC, MinseoSONG commented on app/src/main/java/org/sopt/and/SignUpActivity.kt
> +                        putExtra("password", password.trim())
아하 .. 다른 곳에서의 접근까지 생각해서 상수화했던 거군요 ! 저도 메모 ,,

2024-10-12 21:16 UTC, MinseoSONG commented on app/src/main/java/org/sopt/and/screen/LogInScreen.kt
> +        }
snackbar를 scaffold에서 snackbarHost를 통해 띄울 수 있군요 ??? 참고하고 갑니다 ~ ㅎㅎ

2024-10-12 21:16 UTC, MinseoSONG commented on app/src/main/java/org/sopt/and/screen/LogInScreen.kt
> +            )
이 부분을 SNS계정으로 간편하게 가입하여 이용하실 수 있습니다. 기 text와     존 POOQ 계정 또는 Wavve 게정과는 연동되지 않으 이용에 text로 나누신 이유가 있을까요 ??

2024-10-12 21:16 UTC, MinseoSONG commented on app/src/main/java/org/sopt/and/screen/SignUpScreen.kt
> +
오 상황별 toast 메시지를 구분해두셨군요 ! 참고하겠습니당 ㅎㅎ

2024-10-12 21:16 UTC, MinseoSONG commented on app/src/main/res/values/colors.xml
> +    <color name="profile_gray_25">#FF252525</color>
와 대박 , , 정리킹 !

2024-10-13 05:59 UTC, wjdrjs00 reviewed
1주차 수고하셨습니다!! 다양한 방법 배워갑니다~~!

2024-10-13 05:59 UTC, wjdrjs00 commented on app/src/main/AndroidManifest.xml
> +            android:windowSoftInputMode="adjustResize"
windowSoftInputMode가 어떤 역할을 하는지 궁금합니다??

2024-10-13 05:59 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/and/SignUpActivity.kt
> +                        putExtra("password", password.trim())
저도 배워갑니다!

2024-10-13 05:59 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/and/component/TextFieldCustom.kt
> +    }
개인 취향이긴 한데 전 한줄로 표현하는 방식을 사용했습니다!
한줄로 적는게 좀더 깔끔해 보이기도 하고, 저 기능에서 추가 확장될 부분이 없다 생각했기 때문입니다!

2024-10-13 05:59 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/and/component/TextFieldCustom.kt
> +                }),
키보드 관련설정들 생각못했는데 배워갑니다!

2024-10-13 05:59 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/and/component/TextFieldCustom.kt
> +    val focusManager = LocalFocusManager.current
이건 처음 보는건데 뭔가요?? (진짜 처음봄..ㅎ)

2024-10-13 05:59 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/and/screen/LogInScreen.kt
> +                .background(color = colorResource(R.color.basic_background))
colorResource있군요? 배워갑니다!

2024-10-13 05:59 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/and/screen/LogInScreen.kt
> +                true,
개인적 취향이긴 한데, 명시적으로 표한하는 방식이 좋은거 같습니다!
(처음  볼때 직관적을 파악하기가 좀더 좋다고 생각? 하기 때문입니다..ㅎ)

2024-10-13 05:59 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/and/screen/LogInScreen.kt
> +                    contentDescription = Icons.Default.CheckCircle.name,
contentDescription는 ""로 사용한적이 많았는데 새로운 방법 알고갑니다!

2024-10-13 05:59 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/and/screen/LogInScreen.kt
> +            )
저도 궁금!

2024-10-13 05:59 UTC, wjdrjs00 commented on app/src/main/res/values/colors.xml
> +    <color name="profile_gray_25">#FF252525</color>
앞으로 3조 정리 부탁할게요~

2024-10-13 05:59 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/and/MainActivity.kt
MainActivity를 유지한 이유가 궁금합니다!! (단순 궁금!)

2024-10-13 05:59 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/and/screen/SignUpScreen.kt
> +        "^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d)(?=.*[@#\$%^&+=!])(?=\\S+$).{8,20}$".toRegex()
매직넘버를 방지하는것이 좋다고? 합니다!
저도 이번 미션에서는 구현하진 못했는데 제 생각에는 {8,20} 이 부분에서 사용할 수 있을거 같습니다.(아닐수도.. ㅎ)
(제가 참고했던 블로그 링크 남겨봅니다..! https://velog.io/@devholic/%EC%BD%94%EB%93%9C%EB%A6%AC%EB%B7%B0-%EC%8A%A4%ED%84%B0%EB%94%94-%EC%9E%90%EB%8F%99%EC%B0%A8-%EA%B2%BD%EC%A3%BC-%EB%A7%A4%EC%A7%81-%EB%84%98%EB%B2%84-Magic-Number)

2024-10-13 05:59 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/and/screen/SignUpScreen.kt
> +    val context = LocalContext.current
LocalContext를 활용해서 하는 방법 배워갑니다~
(관련 부분 추가 공부하면서 활용한 블로그 공유해봅니다!
https://velog.io/@haero_kim/Android-Context-%EB%84%88-%EB%8C%80%EC%B2%B4-%EB%AD%90%EC%95%BC )

2024-10-13 05:59 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/and/screen/SignUpScreen.kt
> +        if (!android.util.Patterns.EMAIL_ADDRESS.matcher(id).matches()) {
호오 처음 보는 방식인데 배워갑니다!
이 방식과 이메일 정규식을 직접 구현하는 방식은 어떤 차이점있는지 한번 알아보겠습니다!

2024-10-13 05:59 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/and/screen/MyProfileScreen.kt
> +                    text = "구매하기  >",
호오 전 아이콘을 넣어야 하나 고민하다가 그냥 패스했는데, > 활용 야무집니다!

2024-10-13 09:46 UTC, l2hyunwoo requested changes
안녕하세요 명예오비 이현우입니다.

1주차신데 이미 컴포즈의 많은 부분을 알고 계시는군요! 👍🏻 

이번 코드리뷰에서는 컴포즈를 사용할 때 놓치기 쉬운 부분 위주로 코드리뷰를 해봤습니다. 혹시 이해가 안되는 것 있으시면 언제든지 질문 남겨주세요. 2주차 리뷰 전에 수정부분 피드백 반영해주시면 다시 코드리뷰 남기겠습니다.

2024-10-13 09:46 UTC, l2hyunwoo commented on app/src/main/AndroidManifest.xml
> +            android:theme="@style/Theme.ANDANDROID" />
theme을 application에서 정의해줬는데 activity에서 따로 적용하시는 이유가 있을까요? theme은 어떻게 적용될까요?

2024-10-13 09:46 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/LogInActivity.kt
> +            }
```suggestion
            ANDANDROIDTheme {
                LogInScreen()
            }
```

인덴트는 4칸 or 2칸 정도로 줄여보시는걸 추천드립니다

2024-10-13 09:46 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/component/TextFieldCustom.kt
> +    textfield: String,
- text와 textfield의 차이점이 궁금하군요..!!
- textfield는 `textField`로 수정할 수 있을 것 같네요

2024-10-13 09:46 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/component/TextFieldCustom.kt
> +    showed: Boolean,
[영어 꿀팁]

대부분의 경우에는 해당 컴포넌트가 state 변수에 의해 `수동적`으로 상태가 결정되기 때문에 과거분사형을 적어주는 것이 좋습니다 (be + p.p 오랜만에 들어보죠...?)

그래서 여기서도 showed보단 isShown 정도..!

2024-10-13 09:46 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/component/TextFieldCustom.kt
> +    keyboardOptions: KeyboardOptions,
이건 반드시 넣어줘야하는 값은 아니기 때문에 default parameter 넣어주는 것을 추천드립니다.

2024-10-13 09:46 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/component/TextFieldCustom.kt
> +        Row(verticalAlignment = Alignment.CenterVertically) {
👍🏻

2024-10-13 09:46 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/component/TextFieldCustom.kt
> +    trailingIcon: @Composable (() -> Unit)? = null
오

```suggestion
    trailingIcon: @Composable (() -> Unit)? = null
```

와

```suggestion
    trailingIcon: @Composable (() -> Unit) = {}
```

의 의미론적 차이를 알고 계실까요?

2024-10-13 09:46 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/component/TextFieldCustom.kt
> +    }
```suggestion
    val showPassword = remember(showed) {
      if (!showed) {
          PasswordVisualTransformation()
      } else {
          VisualTransformation.None
      }
    }
```

2024-10-13 09:46 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/component/TextFieldCustom.kt
> +            )
colorResource를 사용할 수 있지만 Theme에서 Color를 정의해주셔도 좋습니다.

2024-10-13 09:46 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/component/TextFieldCustom.kt
> +fun TextAndContent(text: String, content: @Composable () -> Unit) {
이 컴포저블을 따로 분리하신 이유가 있을까요?

2024-10-13 09:46 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/screen/LogInScreen.kt
> +            signUpPassword = result.data?.getStringExtra("password") ?: ""
```suggestion
            signUpId = result.data?.getStringExtra("id").orEmpty()
            signUpPassword = result.data?.getStringExtra("password").orEmpty()
```

이렇게도 적을 수 있다는 사실~

2024-10-13 09:46 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/screen/LogInScreen.kt
> +            signUpPassword = result.data?.getStringExtra("password") ?: ""
근데 이건 개인취향입니다.

2024-10-13 09:46 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/screen/LogInScreen.kt
> +    ) { innerPadding ->
Q) innerPadding의 역할은?

2024-10-13 09:46 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/screen/LogInScreen.kt
> +                true,
컴포즈에서 named argument는 선택이 아니라 (거의) 필수로 권장하고 있습니다.

2024-10-13 09:46 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/screen/LogInScreen.kt
> +                )
👍🏻 

```suggestion
                TextButton(
                    onClick = {
                        showPassword = !showPassword
                    }
                ) {
                       Text(
                            text = "show", modifier = modifier.padding(7.dp)
                        )
                }
```

이렇게 줄일 수 있습니다.

2024-10-13 09:46 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/screen/LogInScreen.kt
> +                                }
```suggestion
                                Toast.makeText(context, "로그인 하였습니다", Toast.LENGTH_SHORT).show()
```

Toast.makeText는 suspend 함수가 아니기 때문에 일반함수 호출하듯이 사용가능합니다.

2024-10-13 09:46 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/screen/LogInScreen.kt
> +                                        Intent.FLAG_ACTIVITY_CLEAR_TASK or Intent.FLAG_ACTIVITY_NEW_TASK
Q) 이 flag의 역할이 뭔지 알고 계신가요?

2024-10-13 09:46 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/screen/LogInScreen.kt
> +                                val intent2 = Intent(context, MyActivity::class.java).apply {
intent2라는 의미는 뭘까요?

2024-10-13 09:46 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/screen/LogInScreen.kt
> +                                    }
```suggestion
                                    SnackbarResult.Dismissed -> Unit
```

2024-10-13 09:46 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/screen/LogInScreen.kt
> +                        .height(50.dp)
@Hyobeen-Park 때로는 버튼이 너무 커져서 화면 컴포넌트 일부가 잠식할 수도 있기 때문에 이런 방식이 더 적절할 수도 있습니다...!! 이것도 때에 따라서 다르게 적용되어야하는 문제일 것 같아요.

2024-10-13 09:46 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/screen/LogInScreen.kt
> +            Spacer(Modifier.padding(10.dp))
```suggestion
            Spacer(Modifier.heigth(10.dp))
```

지금그대로 주시면 높이는 20dp 입니다.

2024-10-13 09:46 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/screen/SignUpScreen.kt
> +        if (!android.util.Patterns.EMAIL_ADDRESS.matcher(id).matches()) {
```suggestion
        if (!Patterns.EMAIL_ADDRESS.matcher(id).matches()) {
```

이렇게 해보시는 것을 추천드립니다!

2024-10-13 09:46 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/screen/SignUpScreen.kt
> +        "^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d)(?=.*[@#\$%^&+=!])(?=\\S+$).{8,20}$".toRegex()
이렇게 구현하시면 매번 리컴포지션에서 regex 변수 재생성할 것 같네요.

2024-10-13 16:09 UTC, wjdrjs00 approved these changes

2024-10-14 03:03 UTC, beom84 commented on app/src/main/AndroidManifest.xml
> +            android:windowSoftInputMode="adjustResize"
키보드자판이 올라올때 화면이 같이 올라가는 기능을 위해 넣었습니다!

2024-10-14 03:40 UTC, beom84 commented on app/src/main/AndroidManifest.xml
> +            android:theme="@style/Theme.ANDANDROID" />
ui.theme package 안에 있는 ANDANDROIDTheme 이라는 composable 함수를 통해 사용되는 것으로 알았습니다.기본적으로  MaterialTheme이 적용되며 원한다면 
새로운 theme을 만들어 color typography shape를 정해줄 수 있다고 알고 있습니다.
다만 Activity에 저런식으로 적용되는건 몰랐습니다!!

2024-10-14 04:38 UTC, beom84 commented on app/src/main/java/org/sopt/and/component/TextFieldCustom.kt
> +    textfield: String,
- Text() TextField() 에 각각 넣을 변수명을 저런식으로 정해보았습니다..!
- 넵. 메모메모!

2024-10-14 04:41 UTC, beom84 commented on app/src/main/java/org/sopt/and/component/TextFieldCustom.kt
> +    keyboardOptions: KeyboardOptions,
넵..! 반드시 넣어줘야 하지않는값 구별 자하기 메모...

2024-10-14 04:47 UTC, beom84 commented on app/src/main/java/org/sopt/and/component/TextFieldCustom.kt
> +    val focusManager = LocalFocusManager.current
textfield간 이동을 편리하게 하려고 넣어보았습니다
textfield안에 focus를 관리해주는 것으로 알고잇습니다

2024-10-14 04:50 UTC, beom84 commented on app/src/main/java/org/sopt/and/component/TextFieldCustom.kt
> +    }
이거또한 기억해줘야 하는 state이군요..! 메모하겠습니다

2024-10-14 04:52 UTC, beom84 commented on app/src/main/java/org/sopt/and/component/TextFieldCustom.kt
> +    }
깔끔한 코드도 너무 좋은거같습니다!메모!

2024-10-14 04:56 UTC, beom84 commented on app/src/main/java/org/sopt/and/component/TextFieldCustom.kt
> +    trailingIcon: @Composable (() -> Unit)? = null
nullable 같은 경우에 함수 호출시 인자가 전달 되지 않으면 trailingIcon 자체가 생성 되지않는 것으로 알고있습니다.
만약 default parameter를 이용한다면 인자가 전달 되지않더라도 빈함수가 rendering 되고 빈 composable 함수가 항상 존재합니다!
여기서는 {}가 더 좋을것 같네요

2024-10-14 05:09 UTC, beom84 commented on app/src/main/java/org/sopt/and/component/TextFieldCustom.kt
> +            )
오..!그러면 한번에 할 수 있어서 편해지겠군요!

2024-10-14 05:10 UTC, beom84 commented on app/src/main/java/org/sopt/and/component/TextFieldCustom.kt
> +fun TextAndContent(text: String, content: @Composable () -> Unit) {
저 content 부분에 나중에 좋아하는 영화 부분을 추가해야하는데 저렇게 하면 조금더 편할거 같아서 분리하였습니다

2024-10-14 05:10 UTC, beom84 commented on app/src/main/java/org/sopt/and/screen/LogInScreen.kt
> +            signUpPassword = result.data?.getStringExtra("password") ?: ""
후욱후욱 제 취향입니다.감사합니다

2024-10-14 05:16 UTC, beom84 commented on app/src/main/java/org/sopt/and/screen/LogInScreen.kt
> +    ) { innerPadding ->
topBar 와 bottomBar의 자리를 padding으로 메꿔준다..!

2024-10-14 05:16 UTC, beom84 commented on app/src/main/java/org/sopt/and/screen/LogInScreen.kt
> +                true,
넵!!!메모!!

2024-10-14 05:21 UTC, beom84 commented on app/src/main/java/org/sopt/and/screen/LogInScreen.kt
> +                )
람다를 잘 활용해보겠습니다!

2024-10-14 05:23 UTC, beom84 commented on app/src/main/java/org/sopt/and/screen/LogInScreen.kt
> +                                }
넵 구별 잘해보겠습니다!

2024-10-14 05:23 UTC, beom84 commented on app/src/main/java/org/sopt/and/screen/LogInScreen.kt
> +                                val intent2 = Intent(context, MyActivity::class.java).apply {
변수명이 겹치지 않기위한 쓰레기네이밍...입니다..

2024-10-14 05:25 UTC, beom84 commented on app/src/main/java/org/sopt/and/screen/LogInScreen.kt
> +                                        Intent.FLAG_ACTIVITY_CLEAR_TASK or Intent.FLAG_ACTIVITY_NEW_TASK
Activity에 중복이 발생했을때 중복을 방지하고 흐름을 제어하기 위해서 사용한다고 배웟습니다!

2024-10-14 05:26 UTC, beom84 commented on app/src/main/java/org/sopt/and/screen/LogInScreen.kt
> +                                    }
오..! 너무 좋습니다

2024-10-14 05:26 UTC, beom84 commented on app/src/main/java/org/sopt/and/screen/LogInScreen.kt
> +                        .height(50.dp)
오...

2024-10-14 05:27 UTC, beom84 commented on app/src/main/java/org/sopt/and/screen/LogInScreen.kt
> +            Spacer(Modifier.padding(10.dp))
와.. 감사합니다 정말 완전 놓치고 있었습니다

2024-10-14 05:28 UTC, beom84 commented on app/src/main/java/org/sopt/and/screen/LogInScreen.kt
> +            )
UI를 notion에 나온데로 icon 위치를 이쁘게 배열하려다 보니 저런식으로 나왔습니다..

2024-10-14 05:31 UTC, beom84 commented on app/src/main/java/org/sopt/and/screen/SignUpScreen.kt
> +    val context = LocalContext.current
감사합니다 읽어보니 너무 좋은 내용이네요!

2024-10-14 05:35 UTC, beom84 commented on app/src/main/java/org/sopt/and/screen/SignUpScreen.kt
> +        "^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d)(?=.*[@#\$%^&+=!])(?=\\S+$).{8,20}$".toRegex()
그렇다면  밖에서 선언하는게 좀더 나은가요?

2024-10-15 02:30 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/component/TextFieldCustom.kt
> +    }
왜 remember를 하는것일까요?

2024-10-15 02:33 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/component/TextFieldCustom.kt
> +fun TextAndContent(text: String, content: @Composable () -> Unit) {
그런 경우에는 해당 컴포저블이 어떤 내응들을 보여주는지 대해 더욱 명확히 설명을 해주는게 중요합니다.

예를 들어서 제가 승범님한테 "참깨빵 위에 순쇠고기 패티 두장 특별한 소스 양상추 치즈 피클 양파까지" 먹으러 가자라고 하면 뭘 먹어야 하는지 모르자나요? "빅맥" 먹으러가자라고 하면 바로 맥도날드를 갈 수 있듯이 이 컴포저블도 이 화면에서 어떤 내용을 보여주는 지 알려주는게 좋아요.

2024-10-15 02:34 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/screen/LogInScreen.kt
> +                )
(참고) 가장 마지막에 오는 lambda는 trailing lambda(트레일링 람다)라고 불러요

2024-10-15 02:34 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/screen/LogInScreen.kt
> +                                        Intent.FLAG_ACTIVITY_CLEAR_TASK or Intent.FLAG_ACTIVITY_NEW_TASK
Activity Flag와 백스택에 대해서 더 공부해보시면 좋을 것 같습니다!

2024-10-15 02:35 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/screen/SignUpScreen.kt
> +        "^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d)(?=.*[@#\$%^&+=!])(?=\\S+$).{8,20}$".toRegex()
방법이 많은데 승범님이 말씀하신 것도 그 방법들 중 하나에요!

2024-10-15 02:38 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/screen/MyProfileScreen.kt
> +    val name = intent?.getStringExtra(SignUpActivity.PROFILEID).orEmpty()
지금 상황에서는 intent에서 name만 꺼내올 수 있는데 어떤 사람이 승범님의 코드에서

```kotlin
    val wrongWords = intent?.getStringExtra("kkk").orEmpty()
```

이런식으로 변수만들어서 실행한다고 하면 어떻게 될까요? 사실 이런 일은 거의 없을건데 이런식으로 다양한 가능성을 열어줄 수 있다는 것도 문제가 발생할 것 같아요.

2024-10-15 03:07 UTC, beom84 commented on app/src/main/java/org/sopt/and/component/TextFieldCustom.kt
> +fun TextAndContent(text: String, content: @Composable () -> Unit) {
아...! 이해가 쏙쏙 알겠습니다

2024-10-15 03:09 UTC, beom84 commented on app/src/main/java/org/sopt/and/screen/MyProfileScreen.kt
> +    val name = intent?.getStringExtra(SignUpActivity.PROFILEID).orEmpty()
헉...이해가 안됩니다... 어떤 문제가 발생하는건가요..

2024-10-16 01:36 UTC, jihyunniiii reviewed
고생하셨습니다 ~

2024-10-16 01:36 UTC, jihyunniiii commented on app/src/main/AndroidManifest.xml
> +            android:theme="@style/Theme.ANDANDROID" />
application에서 정의한 theme은 기본 theme으로 설정되어 모든 activity에 적용됩니다!
그래서 기본 theme를 적용하지 않는 경우에만 (다른 theme를 사용하고 싶은 경우) theme을 설정해주셔도 됩니다!

2024-10-16 01:36 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/SignUpActivity.kt
> +    }
보통 코틀린에서 상수를 정의할 때는 SIGN_UP_ID 이런 식으로 여러 단어를 언더스코어로 구분합니다!

2024-10-16 01:36 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/component/TextFieldCustom.kt
> +            visualTransformation = showPassword, singleLine = true,
```suggestion
            visualTransformation = showPassword,
            singleLine = true,
```
사소하지만,, ! 줄바꿈,,,!

2024-10-16 01:36 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/screen/LogInScreen.kt
> +                }
```suggestion
                SnackbarResult.Dismissed -> Unit
```
일케도 쓸 수 있슴당

2024-10-16 01:36 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/screen/LogInScreen.kt
> +                        .size(50.dp)
list를 사용해보는 것도 좋은 방법일 것 같아요!
반복되는 부분이 많으니까요!

2024-10-16 01:36 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/screen/MyProfileScreen.kt
> +    val name = intent?.getStringExtra(SignUpActivity.PROFILEID).orEmpty()
정의되지 않은 key값을 사용해서 값을 가져오려고 하는 경우 null을 반환합니다. (지금은 key값을 상수화 처리 해두어서 그럴 가능성이 매우 적긴 하지만요.) 이러한 경우를 대비해서 orEmpty()를 사용하는 대신에 null값이 들어올 때 기본 닉네임으로 설정해두는 방법을 사용할 수도 있을 것 같네요!

2024-10-16 01:36 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/screen/MyProfileScreen.kt
> +            )
맞는 것 같슴당! 하나의 Spacer를 사용해서 적절히 처리할 수 있을 것 같아요! (아래 Spacer의 Modifier에 padding을 추가하는 방식 <- 근데 이 때 Modifier의 순서가 조금 중요할 것 같아보이네요)

2024-10-16 01:36 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/screen/SignUpScreen.kt
> +                        "\n" + "Wavve를 즐길 수 있어요!",
```suggestion
                text = "이메일과 비밀번호만으로\nWavve를 즐길 수 있어요!",
```
요렇게 한 번에 적으실 수도 있을 것 같아요!

2024-10-16 01:36 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/screen/LogInScreen.kt
> +            )
기기대응을 고려했을 때는 나누지 않고 한 번에 처리하는 게 나을 수도 있을 것 같다는 생각이 듭니당

2024-10-16 03:31 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/SignUpActivity.kt
> +    }
맞아요!! 코틀린에서는 상수는 UPPER_SNAKE_CASE, 상수가 아닌 이름은 camelCase를 사용합니다!! 

https://developer.android.com/kotlin/style-guide?hl=ko#naming_2

2024-10-16 03:31 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/screen/LogInScreen.kt
> +            )
저도 동의합니다!! 기기의 폰트 크기에 따라 뷰가 다르게 표현될 수 있어요! 저는 화면 크기에 맞게 줄바꿈이 되었으면 좋겠어서 한번에 처리했어요ㅎㅎ 한 줄씩 나오는 것을 원한다면 `.`을 기준으로 나누는 것도 좋을 것 같네요!

2024-10-16 03:31 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/screen/MyProfileScreen.kt
> +            )
헉 맞습니다!! 하나의 Spacer를 사용해서 처리할 수 있어요!! 또한 아래의 Column에서도 처리가 가능해요! 두 가지 방법 모두 Modifier의 순서를 잘 맞추는 것이 중요합니다..!

2024-10-16 04:28 UTC, beom84 commented on app/src/main/java/org/sopt/and/SignUpActivity.kt
> +    }
메모해두겠습니다.

2024-10-16 04:32 UTC, beom84 commented on app/src/main/java/org/sopt/and/screen/SignUpScreen.kt
> +        "^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d)(?=.*[@#\$%^&+=!])(?=\\S+$).{8,20}$".toRegex()
넵!!!

2024-10-16 04:40 UTC, beom84 commented on app/src/main/java/org/sopt/and/screen/MyProfileScreen.kt
> +            )
넵,,,!

2024-10-16 04:45 UTC, beom84 commented on app/src/main/java/org/sopt/and/screen/LogInScreen.kt
> +                )
trailing lambda 이용하기...

2024-10-16 04:55 UTC, beom84 commented on app/src/main/java/org/sopt/and/screen/LogInScreen.kt
> +                        .size(50.dp)
넵!!!1 이런 list 나 regex같은 변수는 어디에 선언하는게 좋나요?

2024-10-16 04:57 UTC, beom84 commented on app/src/main/java/org/sopt/and/screen/LogInScreen.kt
> +                                        Intent.FLAG_ACTIVITY_CLEAR_TASK or Intent.FLAG_ACTIVITY_NEW_TASK
넵!!!

2024-10-16 05:22 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/screen/LogInScreen.kt
> +                text = "Wavve",
저는 하드코딩을 방지하기 위해 UI에 사용되는 문자열들은 대부분 다 추출하고 있어요!

2024-10-16 05:23 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/screen/LogInScreen.kt
> +                        .height(50.dp)
맞습니다!! 특히 지금 과제 뷰에서는 스크롤이 가능하지 않기 때문에 상황에 따라 적절히 적용해야 해요!

2024-10-16 05:30 UTC, Hyobeen-Park approved these changes
1주차 과제 야무지네요ㅎㅎ 수고하셨습니당!

2024-10-16 09:47 UTC, beom84 commented on app/src/main/java/org/sopt/and/screen/LogInScreen.kt
> +            )
넵,,,!

2024-10-25 06:54 UTC, MinseoSONG approved these changes

2024-10-26 11:13 UTC, merged

2025-01-02 06:52 UTC, beom84 commented on app/src/main/java/org/sopt/and/screen/MyProfileScreen.kt
> +    val name = intent?.getStringExtra(SignUpActivity.PROFILEID).orEmpty()
이제는 이해가 된다! 결국 실수를 줄이고 미래를 대비해서 많은 준비를 하라는거군요!! 감사합니다