[Week3] 3주차 필수 과제 구현
AND-SOPT-ANDROID/seungbeom-lee pull request #7
Opened 2024-11-01 09:49 UTC by beom84

## Related issue 🛠
- closed #6 

## Work Description ✏️
- 로그인,회원가입,홈,MY 뷰 설계
- 설계 바탕으로 구현
- 노션 링크 : **[https://www.notion.so/3-13099c2ffa5680369416fbaad41efbaa?pvs=4](url)**
## Screenshot 📸
N/A
## Uncompleted Tasks 😅
- [ ] navigation 분리
## To Reviewers 📢
보고 배우려고 노력중입니다 ..
노션의 그림은 그냥 쓰는 사람이 이상해서 그렇습니다
네비게이션도 고쳐서 얼른 올리겟습니다!!

2024-11-02 07:04 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/ui/ContextExt.kt
> +    @StringRes message: Int,
이런 경우에는 Resource로 뽑아낸 문자열만 스낵바 메시지로 넣을 수 있겠네요.

2024-11-02 07:05 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/ui/ContextExt.kt
> +fun SnackbarHostState.ShowSnackBar(
```suggestion
suspend fun SnackbarHostState.showSnackBar(
```
로 하시면 CoroutineScope 받지 않아도 됩니다.

2024-11-03 12:23 UTC, wjdrjs00 approved these changes
3주차 과제 고생 많으셨습니다!!
2주차 과제 리뷰 통해 리펙토링 하는 모습이 인상 깊습니다!! data class를 각 상태마다 적용하는것도 다시 생각해보니 헷갈려서 실수를 막을 수 있다는 점에서 좋은방법인거 같네요!!
(참고로 노션링크 들어가면 404페이지 나옵니다!!)

2024-11-03 14:43 UTC, Hyobeen-Park reviewed
우와!! 리팩 엄청 많이 하셨네요!! 정말 수고하셨습니다😊

2024-11-03 14:43 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/ui/home/component/MainBannerPager.kt
> +
요기 빈줄!! 하나만 지워주세욤...ㅎㅎ

2024-11-03 14:43 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/ui/login/LogInViewModel.kt
> +                    navigateToMyPage(LogInState(email, password))
흠 화면전환은 뷰모델보다 screen에서 하는 것이 낫지 않을까 싶네요..!! 화면전환은 비즈니스 로직이 아닌 것 같아서요! 지금 sideEffect를 사용하고 계시니까 화면전환도 sideEffect로 관리해보는 것은 어떨까요?

2024-11-03 14:43 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/ui/main/MainTab.kt
> +        contentDescription = "홈",
이것도 string으로 추출하면 좋을 것 같아요!

2024-11-03 14:43 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/ui/main/MainTab.kt
> +    val iconResId: ImageVector,
`ImageVector`를 받는거면 `iconResId`보다는  `icon` / `iconResource` / `iconImageVector` 등으로 바꾸는 것은 어떨까요?

2024-11-03 14:55 UTC, MinseoSONG commented on app/src/main/java/org/sopt/and/ui/home/component/MainBannerPager.kt
> +fun MainBannerPager(bannerList: List<Int>) {
오 배너pager를 컴포넌트화하셨군요 👍 👍

2024-11-03 14:55 UTC, MinseoSONG commented on app/src/main/java/org/sopt/and/ui/login/SignInSideEffect.kt
> +}
우와 toast일 때와 snackbar일 경우를 data class로 나누기 ..  👍 👍

2024-11-04 11:17 UTC, MinseoSONG approved these changes

2024-11-04 15:58 UTC, beom84 commented on app/src/main/java/org/sopt/and/ui/ContextExt.kt
> +fun SnackbarHostState.ShowSnackBar(
헉 감사합니다!!

2024-11-04 15:59 UTC, beom84 commented on app/src/main/java/org/sopt/and/ui/ContextExt.kt
> +    @StringRes message: Int,
그러면 안좋나요??

2024-11-04 16:03 UTC, beom84 commented on app/src/main/java/org/sopt/and/ui/home/component/MainBannerPager.kt
> +
감사합니다!!

2024-11-04 16:03 UTC, beom84 commented on app/src/main/java/org/sopt/and/ui/login/LogInViewModel.kt
> +                    navigateToMyPage(LogInState(email, password))
헉 도전해보겠습니ㅏㄷ!!

2024-11-04 16:03 UTC, beom84 commented on app/src/main/java/org/sopt/and/ui/main/MainTab.kt
> +    val iconResId: ImageVector,
좋습니다 가독성이 좋아질거같아요

2024-11-04 17:53 UTC, l2hyunwoo requested changes
고생하셨습니다. 코드 전반을 살펴보았을 때 코드 동작 원리를 부분적으로 알고 사용하시는 코드들이 많아보입니다. 

우선 사용을 해보시면서 어떻게 동작하는지 감을 잡아보시고 하나하나 코드를 이해하면서 동작 원리까지 이해해가시는것까지 공부하기를 바랍니다. 이번 리뷰는 그 공부를 해나가실 때 가이드라고 생각해보면 좋을 것 같아요.

2024-11-04 17:53 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/ui/component/textfield/UserInfoTextField.kt
> +                onNext = { focusManager.moveFocus(FocusDirection.Down) }
👍🏻

2024-11-04 17:53 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/ui/home/HomeScreen.kt
>      val uiState = homeViewModel.uiState
```suggestion
    val uiState by homeViewModel.uiState
```

2024-11-04 17:53 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/ui/myprofile/component/LikeContentSection.kt
> +    }
이 컴포넌트를 따로 분리한 이유가 있을까요?

2024-11-04 17:53 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/ui/ContextExt.kt
> +    @StringRes message: Int,
왜 안좋을까요? 만약 좋다면 왜 좋을까요? 안좋다고 생각한다면 그에 대한 근거를 같이 한번 생각해보시고 좋다고 생각한다면 마찬가지로 근거를 한번 생각해보세요. 본인이 작성한 코드에는 명확한 이유가 있어야 합니다.

2024-11-04 17:53 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/ui/ContextExt.kt
> +    return result
<img width="670" alt="스크린샷 2024-11-05 오전 2 40 57" src="https://github.com/user-attachments/assets/7e87f95b-3ee6-4748-b50d-a5080860358f">

지금 제가 촬영한 사진의 코드와 위 코드의 연관점을 찾아보시면 좋을 것 같습니다.

2024-11-04 17:53 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/ui/main/MainScreen.kt
> +            if (navigator.shouldShowBottomBar()) {
- Navigator를 `rememberMainNavigator`로 선언해서 가져오는 이유가 있을까요?

2024-11-04 17:53 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/ui/signup/SignUpScreen.kt
> +            }
```suggestion
    LaunchedEffect(Unit) {
        viewModel.signUpSideEffect.flowWithLifecycle(lifecycle = lifecycleOwner.lifecycle)
            .collect { sideEffect ->
                when (sideEffect) {
                    is SignUpSideEffect.ShowToast -> {
                        context.toast(sideEffect.message)
                    }

                    is SignUpSideEffect.ShowSnackBar -> {
                        snackbarHostState.ShowSnackBar(
                            coroutineScope,
                            sideEffect.message,
                            context
                        )
                    }
                }
            }
```

Q) 위와 같이 변경되면 앱 동작에는 어떤 변화가 일어날까요?

2024-11-04 17:53 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/ui/signup/SignUpScreen.kt
> +                            coroutineScope,
이 친구는 왜 key에 안넣으셨나요? key에 넣은 패러미터와 안 넣은 패러미터의 기준이 따로 있으신가요?

2024-11-05 16:05 UTC, beom84 commented
> 고생하셨습니다. 코드 전반을 살펴보았을 때 코드 동작 원리를 부분적으로 알고 사용하시는 코드들이 많아보입니다.
> 
> 우선 사용을 해보시면서 어떻게 동작하는지 감을 잡아보시고 하나하나 코드를 이해하면서 동작 원리까지 이해해가시는것까지 공부하기를 바랍니다. 이번 리뷰는 그 공부를 해나가실 때 가이드라고 생각해보면 좋을 것 같아요.

> 4차과제하면서 제가 만든 코드를 이해하고 목적을 만들어오겠습니다!답변은 그때 한번에 달도록하겠습니다

2024-11-06 06:00 UTC, jihyunniiii reviewed
UI 설계 링크가 안 들어가져요 ㅠㅠ
확인 부탁드립니다.
고생하셨어요 !

2024-11-06 06:00 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/ui/component/textfield/UserInfoTextField.kt
> +    }
nullable 하게 두신 이유가 궁금해요!

2024-11-06 06:00 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/ui/main/MainTab.kt
> +        }
```suggestion
        fun find(predicate: @Composable (MainTabRoute) -> Boolean): MainTab? = entries.find { predicate(it.route) }
```
이렇게 작성할 수도 있습니다.

2024-11-11 07:22 UTC, beom84 commented on app/src/main/java/org/sopt/and/ui/ContextExt.kt
> +    @StringRes message: Int,
좋다고 생각합니다. 함수 사용시에 Resource가 아닌 String을 넣을 경우 오류가 나기 때문에 함수의 일관성을 유지하는데 도움을 준다고 생각합니다

2024-11-11 07:23 UTC, beom84 commented on app/src/main/java/org/sopt/and/ui/main/MainTab.kt
> +        contentDescription = "홈",
넵!

2024-11-11 07:23 UTC, beom84 commented on app/src/main/java/org/sopt/and/ui/home/HomeScreen.kt
>      val uiState = homeViewModel.uiState
by써서 가독성을 늘려보겠습니다

2024-11-11 07:24 UTC, beom84 commented on app/src/main/java/org/sopt/and/ui/myprofile/component/LikeContentSection.kt
> +    }
나중에 좋게 쓰일거라 생각해서 분리했는데 불필요한 컴포넌트 분리인거 같습니다.없애버리겠습니다

2024-11-11 07:27 UTC, beom84 commented on app/src/main/java/org/sopt/and/ui/signup/SignUpScreen.kt
> +            }
key값이 사라지기 때문에 처음 함수가 composition될때 한번 이외에는 실행되지않습니다.Toast나 SnackBar의 경우  recompose안되는경우도 있기때문에 key값은 필요하다고 생각합니다

2024-11-11 07:33 UTC, beom84 commented on app/src/main/java/org/sopt/and/ui/component/textfield/UserInfoTextField.kt
> +    }
다양한 상황에서 사용하기위해서 nullalbe해놓았습니다. 공통 컴포넌트로 쓰면 좋을거같아서요

2024-11-11 07:38 UTC, beom84 commented on app/src/main/java/org/sopt/and/ui/signup/SignUpScreen.kt
> +                            coroutineScope,
혹시 어떤 key값 말씀하시는건가요?

2024-11-11 11:17 UTC, beom84 commented on app/src/main/java/org/sopt/and/ui/ContextExt.kt
> +    return result
코루틴은 비동기적으로 실행되기때문에 println안에는 원하지 않는 sample의 값이 들어갈 수 잇고,
result또한 nullabe로 선언되었지만 원하는 결과가 나오지 않을것 같습니다

2024-11-11 11:17 UTC, beom84 commented on app/src/main/java/org/sopt/and/ui/main/MainTab.kt
> +        }
감사합니다!!!

2024-11-13 02:59 UTC, Hyobeen-Park approved these changes

2024-11-13 04:35 UTC, beom84 commented on app/src/main/java/org/sopt/and/ui/main/MainScreen.kt
> +            if (navigator.shouldShowBottomBar()) {
MainNavgator를 따로 만들어서 나중에 module별로 잘 관리하기 위해서라고 생각하합니다

2024-11-13 04:35 UTC, merged